- name: Update Nemea status dependencies
  yum: "name={{ packages }} state=latest update_cache=yes"

- name: Update Nemea-Supervisor git
  git:
    repo: "{{ git.repo }}"
    dest: "{{ git.dest }}"
    update: true
  notify: Apache restart

- include: common.yml