packages: [unzip, httpd-devel]

pip_packages: [virtualenv, mod_wsgi]

liberoutergui_path: "/var/www/html/liberouter-gui"

liberoutergui: {
  httpdconf: {
    src: "liberouter-gui.conf",
    dest: "/etc/httpd/conf.d/liberouter-gui.conf"
  },
  httpdwsgi: {
    src: "10-wsgi.conf",
    dest: "/etc/httpd/conf.modules.d/10-wsgi.conf"
  },
  htaccess: {
    src: ".htaccess",
    dest: "{{ liberoutergui_path }}"
  },
  conf: {
    src: "{{ liberoutergui_path }}/backend/config-sample.ini",
    dest: "{{ liberoutergui_path }}/backend/config.ini"
  },
  assetsconf: {
    src: "{{ liberoutergui_path }}/assets/config-sample.json",
    dest: "{{ liberoutergui_path }}/assets/config.json"
  },
  nemea: {
    conf_path: "{{ liberoutergui_path }}/backend/liberouterapi/modules/Nemea-Dashboard/config.ini"
  },
  mongodb: {
    db: "nemeadb",
    collection: "alerts_new"
  },
  release: {
    url: "https://github.com/CESNET/liberouter-gui/releases/download/v0.4.0/liberouter-gui-v0.4.0.zip",
    zip: "{{ liberoutergui_path }}/liberouter-gui.zip"
  }
}
