packages: [unzip, httpd-devel]

pip_packages: [virtualenv, mod_wsgi]

liberoutergui_path: "/var/www/html/liberouter-gui"

liberoutergui: {
  httpdconf: {
    src: "liberouter-gui.conf",
    dest: "/etc/httpd/conf.d/liberouter-gui.conf"
  },
  httpdwsgi: {
    src: "10-wsgi.conf",
    dest: "/etc/httpd/conf.modules.d/10-wsgi.conf"
  },
  htaccess: {
    src: ".htaccess",
    dest: "{{ liberoutergui_path }}"
  },
  conf: {
    src: "{{ liberoutergui_path }}/api/config-sample.ini",
    dest: "{{ liberoutergui_path }}/api/config.ini"
  },
  assetsconf: {
    src: "{{ liberoutergui_path }}/assets/config-sample.json",
    dest: "{{ liberoutergui_path }}/assets/config.json"
  },
  nemea: {
    conf_path: "{{ liberoutergui_path }}/api/liberouterapi/modules/nemea/config.ini"
  },
  git_repo: "https://github.com/CESNET/liberouter-gui.git",
  git_tag: "73eea1d18a154805bd97192785203ebdf2b64583",
  release: {
    url: "https://github.com/CESNET/liberouter-gui/releases/download/v0.3.2/liberouter-gui-v0.3.2.zip",
    zip: "{{ liberoutergui_path }}/liberouter-gui.zip"
  }
}
