- name: Install Apache
  yum: "name={{ packages }} state=installed"

- name: Redirect HTTP to HTTPs
  copy:
    src: "{{ apache_redirect_conf.src }}"
    dest: "{{ apache_redirect_conf.dest }}"
  notify: Apache restart

- include: common.yml

- name: Configure Apache SSL
  template:
    src: "{{ apache_ssl_conf.src }}"
    dest: "{{ apache_ssl_conf.dest }}"
  notify: Apache restart

- name: Start & enable Apache
  service: name=httpd enabled=yes state=started
