packages: [nemea, nemea-modules]

repo: {
  nemea: {
    url: "https://copr.fedorainfracloud.org/coprs/g/CESNET/NEMEA/repo/epel-7/group_CESNET-NEMEA-epel-7.repo",
    dest: "/etc/yum.repos.d/COPR-NEMEA.repo"
  },
  mode: 664
}

sample_data: {
  dir: "/data/ipfix_data/"
}

configuration: {
  src: "/usr/share/nemea-supervisor/*",
  dest: "/etc/nemea/",
  creates: "/etc/nemea/config_example.xml",
  local: "{{ inventory_dir }}/host_files/{{ inventory_hostname }}/nemea/"
}

configuration_warden: {
  dest: "/etc/",
  local: "{{ inventory_dir }}/host_files/{{ inventory_hostname }}/warden"
}

warden_client_file: {
  src: "warden_client.py",
  dest: "/usr/lib/python2.7/site-packages/warden_client.py",
  owner: "root",
  group: "root",
  mode: "0664"
}

# path to reporters-config.yml, used by liberouter gui
nemea_reporters_config_path: "/etc/nemea/reporters-config.yml"

nemea_user: "nemead"
nemea_group: "nemead"
