packages: [nemea, nemea-modules]

repo: {
  nemea: {
    url: "https://copr.fedorainfracloud.org/coprs/g/CESNET/NEMEA/repo/epel-7/group_CESNET-NEMEA-epel-7.repo",
    dest: "/etc/yum.repos.d/COPR-NEMEA.repo"
  },
  mode: 664
}

configuration: {
  src: "/usr/share/nemea-supervisor/*",
  dest: "/etc/nemea/",
  creates: "/etc/nemea/config_example.xml",
  local: "{{ inventory_hostname }}/nemea/"
}

configuration_warden: {
  dest: "/etc/",
  local: "{{ playbook_dir }}/files/{{ inventory_hostname }}/warden"
}

warden_client_file: {
  src: "warden_client.py",
  dest: "/usr/lib/python2.7/site-packages/warden_client.py",
  owner: "root",
  group: "root",
  mode: "0664"
}