#!/bin/bash

HOSTNAME=`hostname -f`

/bin/certbot renew --quiet
cp -u /etc/letsencrypt/live/$HOSTNAME/privkey.pem /etc/httpd/certificate/certificate.key
cp -u /etc/letsencrypt/live/$HOSTNAME/fullchain.pem /etc/httpd/certificate/certificate.crt

ISNEW=`find /etc/letsencrypt/live/$HOSTNAME/privkey.pem -mmin +60`
[ -z "$ISNEW" ] && apachectl graceful
