# This file provides some basic checks common to all roles

# This check is not done in when clause since it produces an awful lot of SKIPPED messages (it is used as a dependency in a lot of places)
- name: Check for compatible system
  shell: 'if ! [[ "{{ supported_distributions }}" =~ "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}" ]]; then exit 1; fi'
  changed_when: false
  tags: always

- name: Check for tags
  fail: msg="Use one of [install | update] tags"
  when: tags is not defined
