- name: Install dependencies
  yum: "name={{ packages }} state=installed"

- name: Get python pip
  get_url:
    url: "{{ pip.url }}"
    dest: "{{ pip.tmp }}"

- name: Install python pip
  command: python3.4 "{{ pip.tmp }}" creates="{{ pip.creates }}"