- name: Configuration for Apache
  template:
    src: "{{ liberoutergui.httpdconf.src }}"
    dest: "{{ liberoutergui.httpdconf.dest }}"
  notify: Apache restart

- name: Download Liberouter GUI release
  get_url:
    url: "{{ liberoutergui.release.url }}"
    dest: "{{ liberoutergui.release.zip }}"
    force: yes

- name: Unpack Liberouter GUI release
  unarchive:
    src: "{{ liberoutergui.release.zip }}"
    dest: "{{ liberoutergui_path }}"
    copy: no

- name: Set path in index.html
  lineinfile:
    dest: "{{ liberoutergui_path }}/index.html"
    state: present
    regexp: '<base href=".*>'
    line: '  <base href="/liberouter-gui/">'
  notify: Apache restart

- name: Create Liberouter GUI config
  copy:
    src: "{{ liberoutergui.conf.src }}"
    dest: "{{ liberoutergui.conf.dest }}"
    remote_src: true
  notify: Apache restart

- name: Create Liberouter GUI API path config
  copy:
    src: "{{ liberoutergui.assetsconf.src }}"
    dest: "{{ liberoutergui.assetsconf.dest }}"
    remote_src: true

- name: Set path to reporters configuration file
  lineinfile:
    dest: "{{ liberoutergui.nemea.conf_path }}"
    state: present
    regexp: 'reporters_config =.*'
    line: "reporters_config = {{ nemea_reporters_config_path }}"
  notify: Apache restart

- name: Replace .htaccess with our version
  copy:
    src: "{{ liberoutergui.htaccess.src }}"
    dest: "{{ liberoutergui.htaccess.dest }}"

- name: Install python requirements to virtual environment
  pip:
    requirements: "{{ liberoutergui_path }}/api/requirements.txt"
    virtualenv: "{{ liberoutergui_path }}/api/venv"
    virtualenv_python: python3.4
    virtualenv_site_packages: yes
    state: latest
  notify: Apache restart
