- name: Create templates for nagios-server
  template:
    src: "{{ item }}"
    dest: "{{ config_files.dest }}"
  with_items: "{{ config_files.templates }}"
  notify: Nagios restart

- name: Copy default Nagios configs
  copy:
    src: "{{ item }}"
    dest: "{{ config_files.dest }}"
  with_items: "{{ config_files.configs }}"
  notify: Nagios restart

- name: Check host specific Nagios configs
  local_action: stat path={{ config_files.host }}
  register: nagios_conf_dir
  ignore_errors: True

- name: Copy host specific Nagios configs
  synchronize:
    src: "{{ config_files.host }}"
    dest: "{{ config_files.dest }}"
    archive: no
    recursive: yes
    times: yes
    delete: no
    rsync_opts:
      - "--omit-dir-times"
  notify:
    - Nagios restart
  when: nagios_conf_dir.stat.exists