packages: [munin, munin-node]

config_file: {
  src: "munin.conf",
  dest: "/etc/httpd/conf.d/munin.conf"
}

log_file: {
  dest: "/var/log/munin/munin-cgi-graph.log",
  owner: "{{ apache_user }}",
  group: "{{ apache_group }}",
  mode: "0664"
}

munin_conf: "/etc/munin/munin.conf"

plugin: {
  src: "/usr/share/munin/plugins/nemea_supervisor",
  dest: "/etc/munin/plugins/nemea_supervisor"
}