- name: Install Warden rpm dependencies
  yum: "name={{ packages }} state=installed"

- name: Install Warden pip dependencies
  pip:
    name: "{{ pip_packages }}"
    executable: pip3

- name: Start & enable MariaDB
  service: name=mariadb state=started enabled=yes

- name: Copy Warden install files
  synchronize:
    src: "{{ warden_install_dir.src }}"
    dest: "{{ warden_install_dir.dest }}"
    archive: no
    recursive: yes
    times: yes
    rsync_opts:
      - "--omit-dir-times"

- name: Create Warden keys
  shell: "{{ warden_keys.script }}"
  args:
    creates: "{{ warden_keys.creates }}"

- name: Create Warden database
  shell: "{{ warden_db.script }}"
  args:
     creates: "{{ warden_db.creates }}"

- name: Copy httpd-warden.conf
  copy:
    src: "{{ httpd_warden.conf.src }}"
    dest: "{{ httpd_warden.conf.dest }}"
  notify: Apache-warden restart

- name: Copy httpd-warden
  copy:
    src: "{{ httpd_warden.sysconfig.src }}"
    dest: "{{ httpd_warden.sysconfig.dest }}"
  notify: Apache-warden restart

- name: Copy httpd-warden moudules configuration
  synchronize:
    src: "{{ httpd_warden.modules.src }}"
    dest: "{{ httpd_warden.modules.dest }}"
    archive: no
    recursive: yes
    times: yes
    rsync_opts:
      - "--omit-dir-times"
  notify: Apache-warden restart

- name: Copy httpd-warden.service
  copy:
    src: "{{ httpd_warden.service.src }}"
    dest: "{{ httpd_warden.service.dest }}"
  notify: Apache-warden restart

- name: Copy Warden server
  synchronize:
    src: "{{ warden_server_files.src }}"
    dest: "{{ warden_server_files.dest }}"
    archive: no
    recursive: yes
    times: yes
    rsync_opts:
      - "--omit-dir-times"

- name: Download IDEA schema
  get_url:
    url: "{{ warden_schema.url }}"
    dest: "{{ warden_schema.dest }}"

- name: Install httpd-warden service
  service: name=httpd-warden enabled=yes

- name: Register client to Warden server & create NEMEA config
  shell: "{{ warden_register.script }}"
  args:
    creates: "{{ warden_register.creates }}"
  notify:
    - Restart NEMEA supervisor

