- name: Set default hostname from inventory file
  set_fact: hostname={{ ansible_fqdn }}
  when: hostname is not defined

- name: Set system hostname
  hostname: name={{ hostname }}

- name: Set hostname to /etc/hosts
  lineinfile:
    dest: "{{ hosts_file }}"
    regexp: '^(?!127.0.0.1)[0-9\.]+\s+{{ hostname }}$'
    line: "{{ ansible_default_ipv4.address }} {{ hostname }}"
    state: present
  when: ansible_default_ipv4.address is defined

- name: Set SELinux policy to permissive
  selinux: policy=targeted state=permissive

- name: Set large system receive buffers using sysctl
  copy:
    src: "20-staas.conf"
    dest: "/etc/sysctl.d/20-staas.conf"
  register: sysctl_conf

- name: Activate large system receive buffers
  command: sysctl --system
  when: sysctl_conf.changed

- name: Common tasks
  include: common.yml
