- name: Set default hostname from inventory file
  set_fact: hostname={{ ansible_fqdn }}
  when: hostname is not defined

- name: Set system hostname
  hostname: name={{ hostname }}

- name: Set hostname to /etc/hosts
  lineinfile: dest={{ hosts_file }} regexp='\d+\.\d+\.\d+\.d+\s+{{ hostname }}$' line="{{ ansible_default_ipv4.address }} {{ hostname }}" state=present
  when: ansible_default_ipv4.address is defined

- name: Set SELinux policy to permissive
  selinux: policy=targeted state=permissive

- name: Common tasks
  include: common.yml
