- name: Add IPFIXcol repo
  get_url:
    url: "{{ repo.ipfixcol.url }}"
    dest: "{{ repo.ipfixcol.dest }}"
    mode: "{{ repo.mode }}"

- name: Add NEMEA repo (unirec dependency)
  get_url:
    url: "{{ repo.nemea.url }}"
    dest: "{{ repo.nemea.dest }}"
    mode: "{{ repo.mode }}"

- name: Install IPFIXcol
  yum: "name={{ packages }} state=installed"

- name: Check for host specific startup.xml
  local_action: stat path={{ ipfixcol_startup_xml.host }}
  become: false
  register: host_startup_xml
  ignore_errors: True

- name: Select host specific startup.xml
  set_fact:
    ipfixcol_startup_xml_src: "{{ ipfixcol_startup_xml.host }}"
  when: host_startup_xml.stat.exists

- name: Copy startup.xml configuration template
  copy:
    src: "{{ ipfixcol_startup_xml_src }}"
    dest: "{{ ipfixcol_startup_xml.dest }}"
    force: no
