- name: Add NEMEA repository
  get_url:
    url: "{{ repo.nemea.url }}"
    dest: "{{ repo.nemea.dest }}"
    mode: "{{ repo.mode }}"

- name: Install NEMEA packages
  yum: "name={{ packages }} state=installed"

#- name: Set NEMEA supervisor default configuration
#  shell: >
#    cp -R {{ configuration.src }} {{ configuration.dest }}
#  args:
#    creates: "{{ configuration.creates }}"

- name: Get sample data
  shell: |
    mkdir -p {{ sample_data.dir }}
    wget {{ sample_data_src }} -O {{ sample_data.dir }}/data.ipfix.bz2
    bunzip2 {{ sample_data.dir }}/data.ipfix.bz2
  args:
    creates: "{{ sample_data.dir }}/data.ipfix"
  when: sample_data_src is defined

- name: Common tasks
  include: common.yml

- name: Start NEMEA supervisor
  service: name=nemea-supervisor state=started enabled=yes