- name: Copy Nemea NRPE scripts
  synchronize:
    src: "{{ scripts.src }}"
    dest: "{{ scripts.dest }}"
    archive: no
    recursive: yes
    times: yes
    delete: no
    rsync_opts:
      - "--omit-dir-times"
  notify:
    - Nagios NRPE restart

- name: Copy nagios configs
  copy:
    src: "{{ item }}"
    dest: "{{ config_nrpe.dest }}"
  with_items: "{{ config_nrpe.configs }}"
  notify: Nagios NRPE restart

- name: Get allowed_hosts from nrpe.cfg
  shell: sed -rn 's/^allowed_hosts=(.+)/\1/p' {{ config_nrpe.main }}
  args:
    warn: no
  register: allowed_hosts
  changed_when: false

- name: Update allowed_hosts in nrpe.cfg
  lineinfile:
    dest: "{{ config_nrpe.main }}"
    state: present
    regexp: 'allowed_hosts=.*'
    line: "allowed_hosts={{ (allowed_hosts.stdout.split(',') + groups['nagios_servers'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list) | unique | join(',') }}"
  notify: Nagios NRPE restart

- name: Allow NRPE arguments
  lineinfile:
    dest: "{{ config_nrpe.main }}"
    state: present
    regexp: 'dont_blame_nrpe=.*'
    line: "dont_blame_nrpe=1"
  notify: Nagios NRPE restart

- name: Allow NRPE config dir /etc/nrpe.d/
  lineinfile:
    dest: "{{ config_nrpe.main }}"
    state: present
    line: "include_dir=/etc/nrpe.d/"
  notify: Nagios NRPE restart